baseURL: https://edgarpon-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Edgar
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Masters student at London Business School
    title: Hi, my name is Edgar Pon
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Sussex Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: epon.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: Upon request
        title: Phone
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
   ## copyright: Company Name
    #enable: yes
    #quicklinks:
      #- alt: HTML5 UP
        #text: 'Design: '
        #url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
        #url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/edgar.pon.9/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/edgar.pon/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://github.com/edgarpon
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/edgar-pon
  image: ''
  name: Edgar Pon
  navigation:
    button1:
      - name: Get Started
        url: '#'
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/About_me
      - name: MY R Projects
        url: blogs2
     # - name: Portugal Gapminder Research
      #  url: blogs/Portugal_Study
    menu: Menu
    #subtitle: By HTML5 Up
    #title: Forty
  tiles:
    enable: yes
    showcase:
      - image: my_name.jpg
        subtitle: Lisbon - Macao - Nice - London
        title: About me
        url: blogs/About_me
      - image: cv_pic.jpg
        subtitle: Curriculum Vitae
        title: My Experience
        url: '/files/Edgar Pon CV.pdf'
      - image: portfolio.jpg
        subtitle: Asset Allocation Analysis
        title: Portfolio Construction
        url: '/files/Portfolio Analysis.pdf'
      - image: crime.jpg
        subtitle: Analysis over time
        title: Crime vs Education   
        url: '/files/Crime-education.pdf'
      - image: starbucks.jpg
        subtitle: Competition and Market Power
        title: Starbucks Research
        url: '/files/Starbucks.pdf'
      #- image: pic06.jpg
        #subtitle: Feugiat Amet Tempus
        #title: The hell
        #url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "@Edgar Pon, Made with Academic theme for Hugo"
    title: 
    url: blogs2
